### ISSUE TITLE
How did you choose hyperparameters?

### ISSUE THREAD

**Issue by kumatheworld** [zhanght021/RPT#11]
I have questions about some hyperparameters in the config files.

experiments/siamreppoints/config_vot2018_offline.yaml:
```
TRACK:
    TYPE: 'SiamReppointsTracker'
    PENALTY_K: 0.09384699789214077
    WINDOW_INFLUENCE: 0.2870488747571366
    LR: 0.546949224973851
```
experiments/siamreppoints/config_vot2019_offline.yaml:
```
TRACK:
    TYPE: 'SiamReppointsTracker'
    PENALTY_K: 0.17380070743842363
    WINDOW_INFLUENCE: 0.43745716974756743
    LR: 0.4488453012609389
```
How did you determine those hyperparameters? Why do those values differ in the 2 files?
